services:
  hikamp:
    build: .
    container_name: hikamp
    restart: always
    ports:
      - "10.10.11.5:8081:8080"
    env_file:
      - .env
    environment:
      - TZ=Asia/Jakarta
    networks:
      - app-network

networks:
  app-network:
    external: true
